language: go

go:
  - "1.12"

# magic word to use faster/newer container-based architecture
sudo: false

services:
  - docker

before_install:
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/jteeuwen/go-bindata/...

script:
  - go generate
  - make

  # Build and test the Docker image. It's pushed to Docker Hub as part of the
  # deploy phase.
  - docker build -t "$DOCKER_REPO:${TRAVIS_COMMIT:0:8}" .
  - docker run -d --name telnyx-mock-container -p 12111:12111 "$DOCKER_REPO:${TRAVIS_COMMIT:0:8}"
  - docker ps -a

# deploy:
#   provider: script
#   script: bash scripts/docker_push.sh
#   on:
#     condition: ! -z "$TRAVIS_TAG" || "$TRAVIS_BRANCH" -eq "master"

notifications:
  email:
    on_success: never

# You can create an encrypted variable similar to the one below using:
#
#     travis encrypt --org DOCKER_PASSWORD=password
#
# You'll need the `travis` gem which is correctly configured. For more
# information:
#
#     https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml
#
env:
  global:
    # We're not currently publishing a container, but we'll build it for funsies.
    - DOCKER_REPO="telnyx/telnyx-mock"
    - DOCKER_USERNAME=telnyx
    # the below contains: DOCKER_PASSWORD
    # - secure: "asdfasdfasdf"
